// Generated by Ignite CLI
import { computed } from 'vue'
import { useStore } from 'vuex'

export const useClient = () => {
  const store = useStore()

  const client = computed(() => store.getters['common/env/client'])
  const signer = computed(() => store.getters['common/wallet/signer'])
  const address = computed(() => store.getters['common/wallet/address'])
  const env = computed(() => store.getters['common/env/getEnv'])

  return {
    client,
    signer,
    address,
    env
  }
}
