// Generated by Ignite CLI
import { computed } from 'vue'
import { useStore } from 'vuex'

export const useMechainCheckin = () => {
  const store = useStore()

  const params = computed(() => store.getters['mechain.checkin/getParams'])
  
  const queryParams = (params = {}) => {
    return store.dispatch('mechain.checkin/QueryParams', { 
      options: { subscribe: false, all: false }, 
      params 
    })
  }

  const sendMsgCheckIn = (value, fee = { amount: [], gas: '200000' }, memo = '') => {
    return store.dispatch('mechain.checkin/sendMsgCheckIn', { 
      value, 
      fee, 
      memo 
    })
  }

  const msgCheckIn = (value) => {
    return store.dispatch('mechain.checkin/MsgCheckIn', { value })
  }

  return {
    params,
    queryParams,
    sendMsgCheckIn,
    msgCheckIn
  }
}
